[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "numdf"
version = "0.1"
dependencies = ["firedrake", "numpy"]

[project.optional-dependencies]
doc = ["sphinx"]