name: Build the docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  # Cancels jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # Build job
  build_docs:
    name: Run doc build
    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake:latest
      options: --user root
    
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      
      # This is an action that checks out your repository onto the runner, 
      # allowing you to run scripts or other actions against your code (such as build and test tools)
      - name: Checkout
        uses: actions/checkout@v4
      
      # Activate firedrake and install dependencies
      - name: Install NumDF
        run: |
          python3 -m pip install -e .

      - name: Build docs
        run: |
          cd docs
          make html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: /__w/Numdf/Numdf/docs/build/html
          retention-days: 1
  
  
  # Deployment job
  deploy:
    name: Deploy Github pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4