# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: "Build CHIST"
    
    runs-on: ubuntu-latest

    container:
      image: firedrakeproject/firedrake-vanilla:latest    
    
    steps:
      
      # This is an action that checks out your repository onto the runner, 
      # allowing you to run scripts or other actions against your code (such as build and test tools)
      - uses: actions/checkout@v4

      # Activate firedrake and install dependencies
      - name: Install CHIST
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install -e .
          python -m pip install  pytest-timeout
      
      # Run tests with pytest
      - name: CHIST tests
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pytest