# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: "Build CHIST"
    # The type of runner that the job will run on

    # Run on our self-hosted machines
    runs-on: self-hosted

    container:
      image: firedrakeproject/firedrake-vanilla:latest    
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build
