# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build NumDF"
    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake-vanilla-default:latest
      options: --user root
    
    steps:
      
      # This is an action that checks out your repository onto the runner, 
      # allowing you to run scripts or other actions against your code (such as build and test tools)
      - name: Checkout
        uses: actions/checkout@v4
    
      # Activate firedrake and install dependencies
      - name: Install NumDF
        run: |
          python3 -m pip install -e .
      
      # Run tests with pytest
      - name: NumDF tests
        run: |
          python3 -m pip install pytest
          python3 -m pytest -v tests/
